services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME}
      - WEBHOOK_PASSWORD=${WEBHOOK_PASSWORD}
      - MCRM_API_URL_USER=${MCRM_API_URL_USER}
      - MCRM_API_URL_BONUS=${MCRM_API_URL_BONUS}
      - MCRM_API_TOKEN=${MCRM_API_TOKEN}
      - LISTMONK_API_URL=${LISTMONK_API_URL}
      - LISTMONK_API_USER=${LISTMONK_API_USER}
      - LISTMONK_API_TOKEN=${LISTMONK_API_TOKEN}
      - BONUS_SUM=${BONUS_SUM}
      - LIST_ID=${LIST_ID}
      - DB_HOST=postgres_db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    depends_on:
      - postgres_db
    networks:
      - app-network
    restart: unless-stopped

  postgres_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge