import xml.etree.ElementTree as ET
import asyncio

# словарь с названиями цветов и путями к изображениям
color_images = {
    "мягкое мороженое": "color_images/F302.png",
    "маслянисто-лимонный": "color_images/G302.png",
    "лимонный мусс": "color_images/H302.png",
    "солнечно-желтый": "color_images/J302.png",
    "лютиковый желтый": "color_images/K302.png",
    "фрезия": "color_images/L302.png",
    "шафрановый желтый": "color_images/M302.png",
    "насыщенный желтый": "color_images/N302.png",
    "цейлонский желтый": "color_images/S302.png",
    "цвет пампасной травы": "color_images/V302.png",
    "желтая роза": "color_images/X302.png",
    "слоновая кость": "color_images/Y302.png",
    "молочно-ванильный": "color_images/F303.png",
    "ваниль": "color_images/G303.png",
    "абрикосовое мороженое": "color_images/H303.png",
    "льняной": "color_images/J303.png",
    "светлый янтарно-желтый": "color_images/K303.png",
    "карри": "color_images/L303.png",
    "янтарный": "color_images/M303.png",
    "медово-желтый": "color_images/N303.png",
    "насыщенный золотой": "color_images/S303.png",
    "цвет желтой глины": "color_images/V303.png",
    "палевый (кожи буйвола)": "color_images/X303.png",
    "заварной крем": "color_images/Y303.png",
    "молочно-белый": "color_images/F307.png",
    "мягкий оттенок белого камня": "color_images/G307.png",
    "солнце сахары": "color_images/H307.png",
    "светлая осень": "color_images/J307.png",
    "пастельно-желтый": "color_images/K307.png",
    "умеренный оранжево-желтый": "color_images/L307.png",
    "тыквенный": "color_images/M307.png",
    "восковый": "color_images/N307.png",
    "умеренный желтый": "color_images/S307.png",
    "золотой туман": "color_images/V307.png",
    "овсяный": "color_images/X307.png",
    "белый антик": "color_images/Y307.png",
    "цветочный белый": "color_images/F309.png",
    "винтажное кружево": "color_images/G309.png",
    "перламутр": "color_images/H309.png",
    "оранжево-розовый светлый": "color_images/J309.png",
    "светлая календула": "color_images/K309.png",
    "календула": "color_images/L309.png",
    "абрикос": "color_images/M309.png",
    "оранжевый": "color_images/N309.png",
    "мандарин": "color_images/S309.png",
    "апельсиновый": "color_images/V309.png",
    "замшевый": "color_images/X309.png",
    "желто-персиковый": "color_images/Y309.png",
    "бело-розовый фарфор": "color_images/F323.png",
    "цветок миндаля": "color_images/G323.png",
    "клубничный мусс": "color_images/H323.png",
    "тосканский розовый": "color_images/J323.png",
    "пионово-розовый": "color_images/K323.png",
    "амарантовый красный": "color_images/L323.png",
    "помадный красный": "color_images/M323.png",
    "академический красный": "color_images/N323.png",
    "малиново-розовый": "color_images/S323.png",
    "цвет старой розы": "color_images/V323.png",
    "пастельный розовый": "color_images/X323.png",
    "цвет сладкой ваты": "color_images/Y323.png",
    "розовый лотос": "color_images/F327.png",
    "клубничный шербет": "color_images/G327.png",
    "цвет душистого горошка": "color_images/H327.png",
    "антуриум": "color_images/J327.png",
    "яркий амарантовый": "color_images/K327.png",
    "малиновый": "color_images/L327.png",
    "клюквенный": "color_images/M327.png",
    "гранатовый красный": "color_images/N327.png",
    "душистая клубника": "color_images/S327.png",
    "цвет лепестков розы": "color_images/V327.png",
    "средне-розовый": "color_images/X327.png",
    "легкий розовый": "color_images/Y327.png",
    "нежно-розовый": "color_images/F332.png",
    "английская роза": "color_images/H332.png",
    "натуральный розовый": "color_images/J332.png",
    "турецкий лукум": "color_images/K332.png",
    "ягодный": "color_images/L332.png",
    "винно-красный": "color_images/M332.png",
    "глубокий рубиновый": "color_images/N332.png",
    "брусничный": "color_images/S332.png",
    "роза барокко": "color_images/V332.png",
    "рассветный розовый": "color_images/X332.png",
    "дымчато-розовый": "color_images/Y332.png",
    "кремово-розовый": "color_images/F336.png",
    "маршмеллоу": "color_images/G336.png",
    "цвет розовой гвоздики": "color_images/H336.png",
    "фламинго": "color_images/J336.png",
    "гламурный розовый": "color_images/K336.png",
    "сочный малиновый": "color_images/L336.png",
    "свекольный": "color_images/N336.png",
    "цвет сангрии": "color_images/S336.png",
    "лилово-розовый": "color_images/V336.png",
    "розовато-лиловый светлый": "color_images/X336.png",
    "розовый кварц": "color_images/Y336.png",
    "арктический лед": "color_images/F358.png",
    "голубой лед": "color_images/G358.png",
    "голубой мираж": "color_images/H358.png",
    "васильковый светлый": "color_images/J358.png",
    "пронзительный голубой": "color_images/K358.png",
    "кобальт": "color_images/L358.png",
    "глубоководный синий": "color_images/M358.png",
    "ультрамарин": "color_images/N358.png",
    "небесно-голубой": "color_images/S358.png",
    "младенческий голубой": "color_images/V358.png",
    "сумеречно-голубой": "color_images/X358.png",
    "морозный иней": "color_images/F363.png",
    "пасмурно-небесный": "color_images/G363.png",
    "светло-голубой": "color_images/H363.png",
    "цвет голубой глины": "color_images/J363.png",
    "адриатический синий": "color_images/K363.png",
    "темно-лазурный": "color_images/L363.png",
    "берлинская лазурь": "color_images/M363.png",
    "океанический синий": "color_images/N363.png",
    "ниагарский водопад": "color_images/S363.png",
    "синий дым": "color_images/V363.png",
    "голубой топаз": "color_images/X363.png",
    "морозная лазурь": "color_images/F366.png",
    "аква": "color_images/G366.png",
    "аквамарин": "color_images/H366.png",
    "свежий бриз": "color_images/J366.png",
    "лазурный": "color_images/K366.png",
    "голубая лагуна": "color_images/L366.png",
    "черное море": "color_images/M366.png",
    "глубокий атлантический": "color_images/N366.png",
    "морская волна": "color_images/S366.png",
    "синий шторм": "color_images/V366.png",
    "снежно-синий": "color_images/X366.png",
    "очень светлый бирюзовый": "color_images/G368.png",
    "светлый бирюзовый": "color_images/H368.png",
    "голубино-сизый": "color_images/J368.png",
    "водная синь": "color_images/K368.png",
    "мурена": "color_images/L368.png",
    "глубокий темно-бирюзовый": "color_images/M368.png",
    "серо-бирюзовый": "color_images/N368.png",
    "аспидно-синий": "color_images/S368.png",
    "цвет утиного яйца": "color_images/V368.png",
    "венская зелень": "color_images/H382.png",
    "крыжовник": "color_images/J382.png",
    "зеленое яблоко": "color_images/K382.png",
    "шартрез": "color_images/L382.png",
    "лиственно-зеленый": "color_images/M382.png",
    "кленовый зеленый": "color_images/N382.png",
    "нефритовый зеленый": "color_images/S382.png",
    "светлый нефрит": "color_images/V382.png",
    "чайное дерево": "color_images/X382.png",
    "мягкий оттенок мяты": "color_images/H384.png",
    "цвет перечной мяты": "color_images/J384.png",
    "Эвкалиптовый": "color_images/K384.png",
    "зеленый папоротник": "color_images/L384.png",
    "спаржевый": "color_images/M384.png",
    "хвойный зеленый": "color_images/N384.png",
    "кипарис": "color_images/S384.png",
    "полынный": "color_images/V384.png",
    "сероватый мятный": "color_images/X384.png",
    "разбеленный салатовый": "color_images/F387.png",
    "бледно-салатовый": "color_images/G387.png",
    "светлый фисташковый": "color_images/H387.png",
    "салатовый": "color_images/J387.png",
    "фисташковый": "color_images/K387.png",
    "средне-зеленый": "color_images/L387.png",
    "песто": "color_images/M387.png",
    "цвет еловой хвои": "color_images/N387.png",
    "травяной зеленый": "color_images/S387.png",
    "мякоть лайма": "color_images/V387.png",
    "цвет зеленого горошка": "color_images/X387.png",
    "ванильно-лаймовый": "color_images/F388.png",
    "лимонно-лаймовое безе": "color_images/G388.png",
    "лаймовый шербет": "color_images/H388.png",
    "светлый грушевый": "color_images/J388.png",
    "лемонграсс": "color_images/K388.png",
    "лайм": "color_images/L388.png",
    "темный лаймовый": "color_images/M388.png",
    "авокадо": "color_images/N388.png",
    "бергамот": "color_images/S388.png",
    "фисташковый пломбир": "color_images/V388.png",
    "светлый лайм": "color_images/X388.png",
    "восход": "color_images/F401.png",
    "золотисто-персиковый": "color_images/G401.png",
    "марципан": "color_images/H401.png",
    "золотисто-коричневый": "color_images/J401.png",
    "сепия": "color_images/K401.png",
    "охра": "color_images/L401.png",
    "тоффи": "color_images/M401.png",
    "корица": "color_images/N401.png",
    "фундук": "color_images/S401.png",
    "пралине": "color_images/V401.png",
    "розовый древесный": "color_images/X401.png",
    "фарфорово-бежевый": "color_images/Y401.png",
    "молочный опал": "color_images/F405.png",
    "яблоневый цвет": "color_images/G405.png",
    "пудрово-персиковый": "color_images/H405.png",
    "сомон": "color_images/J405.png",
    "яблоко с корицей": "color_images/K405.png",
    "печеное яблоко": "color_images/L405.png",
    "терракотово-коричный": "color_images/M405.png",
    "красное дерево": "color_images/N405.png",
    "ржаво-оранжевый": "color_images/S405.png",
    "карамель": "color_images/V405.png",
    "карамельно-розовый": "color_images/X405.png",
    "бледный кизил": "color_images/Y405.png",
    "розовый опал": "color_images/F406.png",
    "розовый закат": "color_images/G406.png",
    "каирская роза": "color_images/H406.png",
    "жареный миндаль": "color_images/J406.png",
    "закат сахары": "color_images/K406.png",
    "цвет сырой охры": "color_images/L406.png",
    "гончарная глина": "color_images/M406.png",
    "рыжий": "color_images/N406.png",
    "глиняный": "color_images/S406.png",
    "кленовый сироп": "color_images/V406.png",
    "миндальное печенье": "color_images/X406.png",
    "персиковый нюд": "color_images/Y406.png",
    "коралловое облако": "color_images/F411.png",
    "розовая пудра": "color_images/G411.png",
    "персиковый сорбет": "color_images/H411.png",
    "розовый мак": "color_images/J411.png",
    "герань": "color_images/K411.png",
    "паприка": "color_images/L411.png",
    "багряный": "color_images/M411.png",
    "калина": "color_images/N411.png",
    "кирпичный": "color_images/S411.png",
    "тоскана": "color_images/V411.png",
    "пыльный коралл": "color_images/X411.png",
    "розовая камея": "color_images/Y411.png",
    "серебристо-лиловый": "color_images/F428.png",
    "вечерняя мгла": "color_images/G428.png",
    "светлый ламантин": "color_images/H428.png",
    "ламантин": "color_images/J428.png",
    "перламутровый ежевичный": "color_images/K428.png",
    "ночная тень": "color_images/L428.png",
    "глубокий черничный": "color_images/M428.png",
    "сланцево-серый": "color_images/N428.png",
    "светлый сланцевый": "color_images/S428.png",
    "платиновый серый": "color_images/V428.png",
    "серовато-фарфоровый": "color_images/X428.png",
    "платина": "color_images/Y428.png",
    "полярный голубой": "color_images/F431.png",
    "цвет голубого колокольчика": "color_images/H431.png",
    "сине-голубой": "color_images/J431.png",
    "синий деним": "color_images/K431.png",
    "перламутровый ночной": "color_images/L431.png",
    "индиго": "color_images/M431.png",
    "полночная синь": "color_images/N431.png",
    "грозовое небо": "color_images/S431.png",
    "деним": "color_images/V431.png",
    "пепельно-льдистый": "color_images/F435.png",
    "циркон": "color_images/G435.png",
    "веджвуд": "color_images/K435.png",
    "вечерний синий": "color_images/M435.png",
    "космический синий": "color_images/N435.png",
    "дымчато-голубой": "color_images/S435.png",
    "серый агат": "color_images/V435.png",
    "морская пена": "color_images/X435.png",
    "капли дождя": "color_images/F436.png",
    "сизый цвет дикой утки": "color_images/N436.png",
    "свинцовый": "color_images/S436.png",
    "ванильно-серый": "color_images/F457.png",
    "натуральный цвет камня": "color_images/H457.png",
    "галечный серый": "color_images/J457.png",
    "табачный": "color_images/N457.png",
    "пудра": "color_images/G472.png",
    "орехово-розовый": "color_images/J472.png",
    "ореховый": "color_images/L472.png",
    "жареный каштан": "color_images/M472.png",
    "теплый ореховый": "color_images/S472.png",
    "миндальная пудра": "color_images/X472.png",
    "легкий румянцевый": "color_images/F476.png",
    "розовый цикорий": "color_images/J476.png",
    "красный цикорий": "color_images/K476.png",
    "красновато-коричневый": "color_images/M476.png",
    "шоколадный трюфель": "color_images/S476.png",
    "махагоновый": "color_images/L478.png",
    "темный махагон": "color_images/M478.png",
    "ромовый изюм": "color_images/N478.png",
    "миндальный крем": "color_images/F480.png",
    "какао-мусс": "color_images/G480.png",
    "какао с молоком": "color_images/H480.png",
    "натуральная пенька": "color_images/J480.png",
    "шоколадный пломбир": "color_images/K480.png",
    "молочный шоколад": "color_images/L480.png",
    "горький шоколад": "color_images/M480.png",
    "шоколад": "color_images/N480.png",
    "кашемировая шерсть": "color_images/V480.png",
    "белая ночь": "color_images/F484.png",
    "устрично-бежевый": "color_images/G484.png",
    "разбеленный кофейный": "color_images/H484.png",
    "кофе латте": "color_images/J484.png",
    "кофе фраппе": "color_images/K484.png",
    "пряный эспрессо": "color_images/L484.png",
    "каштановый": "color_images/M484.png",
    "капуччино": "color_images/N484.png",
    "мокко": "color_images/S484.png",
    "серый сланцевый": "color_images/X484.png",
    "кварц": "color_images/Y484.png",
    "сумеречный серый": "color_images/F488.png",
    "французский серый": "color_images/G488.png",
    "муссон": "color_images/H488.png",
    "каменно-серый": "color_images/J488.png",
    "серый": "color_images/K488.png",
    "дымчатый серый": "color_images/L488.png",
    "глубокий серый": "color_images/M488.png",
    "мокрый асфальт": "color_images/N488.png",
    "лакрица": "color_images/S488.png",
    "черный": "color_images/Y488.png",
    "крем-брюле": "color_images/F311.png",
    "кремовый абрикосовый": "color_images/G311.png",
    "абрикосовый шербет": "color_images/H311.png",
    "теплый абрикосовый": "color_images/J311.png",
    "медово-абрикосовый": "color_images/K311.png",
    "охристый": "color_images/L311.png",
    "желтый кадмий": "color_images/M311.png",
    "медно-рыжий": "color_images/N311.png",
    "мягкий медно-оранжевый": "color_images/S311.png",
    "топаз": "color_images/V311.png",
    "бежевый": "color_images/X311.png",
    "телесный": "color_images/Y311.png",
    "персиковый лед": "color_images/F314.png",
    "песок пустыни": "color_images/G314.png",
    "персик в сливках": "color_images/H314.png",
    "нектарин": "color_images/J314.png",
    "терракота": "color_images/K314.png",
    "цвет хурмы": "color_images/L314.png",
    "морковный": "color_images/M314.png",
    "пряный оранжевый": "color_images/N314.png",
    "светло-морковный": "color_images/S314.png",
    "карамельно-персиковый": "color_images/X314.png",
    "бледно-персиковый": "color_images/Y314.png",
    "мягкий розовый": "color_images/F319.png",
    "цвет розовой воды": "color_images/G319.png",
    "флер-д-оранж": "color_images/H319.png",
    "коралловая дымка": "color_images/J319.png",
    "танжерин": "color_images/K319.png",
    "цвет кайенского перца": "color_images/L319.png",
    "пламенный красный": "color_images/M319.png",
    "карминный красный": "color_images/N319.png",
    "паприка": "color_images/S319.png",
    "персиковый": "color_images/V319.png",
    "темный пудровый": "color_images/X319.png",
    "жемчужный": "color_images/Y319.png",
    "цвет перламутровой раковины": "color_images/F320.png",
    "приглушенный персиковый": "color_images/G320.png",
    "лососево-розовый": "color_images/H320.png",
    "львиный зев": "color_images/J320.png",
    "коралловый": "color_images/K320.png",
    "алый": "color_images/L320.png",
    "маковый красный": "color_images/M320.png",
    "театральный красный": "color_images/N320.png",
    "киноварь": "color_images/S320.png",
    "розовый антик": "color_images/V320.png",
    "цвет розового кизила": "color_images/X320.png",
    "розовый кристалл": "color_images/Y320.png",
    "райский розовый": "color_images/F338.png",
    "розовое парфе": "color_images/G338.png",
    "камелия": "color_images/H338.png",
    "Эпатажный розовый": "color_images/J338.png",
    "неоновый розовый": "color_images/K338.png",
    "маджента": "color_images/L338.png",
    "фуксия": "color_images/M338.png",
    "цвет красной сливы": "color_images/N338.png",
    "мальва": "color_images/S338.png",
    "маджентовая дымка": "color_images/V338.png",
    "лавандово-розовый": "color_images/X338.png",
    "Йогуртовый розовый": "color_images/Y338.png",
    "цвет розовой примулы": "color_images/F342.png",
    "розовый туман": "color_images/G342.png",
    "лаванда": "color_images/H342.png",
    "вереск": "color_images/J342.png",
    "аметист": "color_images/K342.png",
    "насыщенный пурпурный": "color_images/L342.png",
    "тёмно-пурпурный": "color_images/M342.png",
    "черничный": "color_images/N342.png",
    "фиалка": "color_images/S342.png",
    "сияющая орхидея": "color_images/V342.png",
    "глициния": "color_images/X342.png",
    "мягкий лавандовый": "color_images/Y342.png",
    "ледник": "color_images/F351.png",
    "фарфорово-голубой": "color_images/G351.png",
    "дымчато-голубой": "color_images/H351.png",
    "нежный сиреневый": "color_images/J351.png",
    "оттенок гиацинта": "color_images/K351.png",
    "имперский пурпур": "color_images/L351.png",
    "глубокий пурпурно-синий": "color_images/M351.png",
    "средиземное море": "color_images/N351.png",
    "виола": "color_images/S351.png",
    "розмариновый": "color_images/V351.png",
    "перванш": "color_images/X351.png",
    "светлый серо-голубой": "color_images/Y351.png",
    "лунный камень": "color_images/F355.png",
    "весеннее небо": "color_images/G355.png",
    "цветок незабудки": "color_images/H355.png",
    "синий прованс": "color_images/J355.png",
    "колокольчиковый синий": "color_images/K355.png",
    "королевский синий": "color_images/L355.png",
    "глубокий чернильный": "color_images/M355.png",
    "сапфир": "color_images/N355.png",
    "синий лазурит": "color_images/S355.png",
    "серо-голубой": "color_images/V355.png",
    "французский голубой": "color_images/X355.png",
    "воздушный голубой": "color_images/Y355.png",
    "разбеленный мятный": "color_images/F370.png",
    "ледяной ментоловый": "color_images/G370.png",
    "пастельно-бирюзовый": "color_images/H370.png",
    "прохладный бирюзовый": "color_images/J370.png",
    "средне-бирюзовый": "color_images/K370.png",
    "атлантида": "color_images/L370.png",
    "насыщенный изумрудный": "color_images/M370.png",
    "изумрудный": "color_images/N370.png",
    "зеленая патина": "color_images/S370.png",
    "припыленный бирюзовый": "color_images/V370.png",
    "морская пена": "color_images/X370.png",
    "холодный светло-бирюзовый": "color_images/Y370.png",
    "снежный мятный": "color_images/G372.png",
    "мятное мороженое": "color_images/H372.png",
    "ментоловый": "color_images/J372.png",
    "тиффани": "color_images/K372.png",
    "цветущий луг": "color_images/L372.png",
    "опаловый зеленый": "color_images/M372.png",
    "зеленая сосна": "color_images/N372.png",
    "персидский зеленый": "color_images/S372.png",
    "нежная мята": "color_images/V372.png",
    "нежный мятно-голубой": "color_images/X372.png",
    "мятно-кремовый": "color_images/F375.png",
    "светлый мятный": "color_images/G375.png",
    "зеленая мята": "color_images/H375.png",
    "трилистник": "color_images/J375.png",
    "холодный зеленый": "color_images/K375.png",
    "малахитовый зеленый": "color_images/L375.png",
    "бутылочный зеленый": "color_images/M375.png",
    "темно-зеленый": "color_images/N375.png",
    "мягкий оттенок папоротника": "color_images/S375.png",
    "цвет жимолости": "color_images/V375.png",
    "акриловый зеленый": "color_images/X375.png",
    "мятный пломбир": "color_images/F380.png",
    "зеленый чай": "color_images/G380.png",
    "виноградно-зеленый": "color_images/H380.png",
    "весенняя зелень": "color_images/J380.png",
    "травянистый зеленый": "color_images/K380.png",
    "лесная зелень": "color_images/L380.png",
    "насыщенный зеленый": "color_images/M380.png",
    "миртовый": "color_images/N380.png",
    "темный весенне-зеленый": "color_images/S380.png",
    "аспарагус": "color_images/V380.png",
    "светлый аспарагус": "color_images/X380.png",
    "бледно-зеленый": "color_images/Y380.png",
    "медовая роса": "color_images/F390.png",
    "выбеленный лен": "color_images/G390.png",
    "банановый крем": "color_images/H390.png",
    "лимонный шербет": "color_images/J390.png",
    "цитрусовый лимонад": "color_images/K390.png",
    "дюшес": "color_images/L390.png",
    "насыщенный грушевый": "color_images/M390.png",
    "грушевый": "color_images/N390.png",
    "липовый желто-зеленый": "color_images/S390.png",
    "бамбуковый желтый": "color_images/V390.png",
    "бледный лимонный": "color_images/X390.png",
    "сгущеное молоко": "color_images/F392.png",
    "пина колада": "color_images/G392.png",
    "песочный": "color_images/J392.png",
    "пряная горчица": "color_images/K392.png",
    "дижонская горчица": "color_images/L392.png",
    "античное золото": "color_images/M392.png",
    "бронзовый": "color_images/N392.png",
    "золото": "color_images/S392.png",
    "соломенно-желтый": "color_images/X392.png",
    "светлый соломенный": "color_images/Y392.png",
    "брызги шампанского": "color_images/F393.png",
    "солнечный лимонный": "color_images/G393.png",
    "лимонная меренга": "color_images/H393.png",
    "натуральный пшеничный": "color_images/J393.png",
    "золотистый": "color_images/K393.png",
    "темное золото": "color_images/L393.png",
    "латунный": "color_images/M393.png",
    "золотой дуб": "color_images/N393.png",
    "мягкая карамель": "color_images/S393.png",
    "ореховая нуга": "color_images/V393.png",
    "бисквитный": "color_images/X393.png",
    "Экрю": "color_images/F398.png",
    "перламутровый бежевый": "color_images/G398.png",
    "светлый пшеничный": "color_images/H398.png",
    "палевый": "color_images/J398.png",
    "шамоа (цвет верблюжей шерсти)": "color_images/K398.png",
    "медовый": "color_images/L398.png",
    "натуральная умбра": "color_images/M398.png",
    "коричневый охристый": "color_images/N398.png",
    "желто-коричневый": "color_images/S398.png",
    "песочно-желтый": "color_images/V398.png",
    "сладкое печенье": "color_images/X398.png",
    "бискотти": "color_images/Y398.png",
    "розовый мрамор": "color_images/F416.png",
    "розовый вечер": "color_images/G416.png",
    "пепельная роза": "color_images/H416.png",
    "медно-розовый": "color_images/J416.png",
    "розовый бренди": "color_images/K416.png",
    "гвоздика": "color_images/L416.png",
    "бурый оттенок хны": "color_images/M416.png",
    "коньячный": "color_images/N416.png",
    "имбирный пряник": "color_images/S416.png",
    "мускатный орех": "color_images/V416.png",
    "яблочный чатни": "color_images/X416.png",
    "чайная роза": "color_images/Y416.png",
    "розовый зефир": "color_images/F419.png",
    "прохладный розовый": "color_images/G419.png",
    "мускатный розовый": "color_images/H419.png",
    "румяный": "color_images/J419.png",
    "марсала": "color_images/K419.png",
    "имбирный": "color_images/L419.png",
    "бургундский": "color_images/M419.png",
    "спелая вишня": "color_images/N419.png",
    "приглушенный гранатовый": "color_images/S419.png",
    "мусс спелой вишни": "color_images/V419.png",
    "оттенок увядшей розы": "color_images/X419.png",
    "вербена розовая": "color_images/F424.png",
    "розовый ландыш": "color_images/G424.png",
    "сладкий лиловый": "color_images/H424.png",
    "тубероза": "color_images/J424.png",
    "турмалиновый розовый": "color_images/K424.png",
    "приглушенный брусничный": "color_images/L424.png",
    "божоле": "color_images/M424.png",
    "черная смородина": "color_images/N424.png",
    "виноградный глинтвейн": "color_images/S424.png",
    "лиловый": "color_images/V424.png",
    "лавандовая дымка": "color_images/X424.png",
    "цвет дымчатой орхидеи": "color_images/Y424.png",
    "оттенок орхидеи": "color_images/F426.png",
    "мягкий лунно-лиловый": "color_images/G426.png",
    "серо-лиловый": "color_images/H426.png",
    "перепелиный": "color_images/J426.png",
    "морской туман": "color_images/K426.png",
    "инжир": "color_images/L426.png",
    "чернослив": "color_images/M426.png",
    "ежевичный": "color_images/N426.png",
    "светлый ежевичный": "color_images/S426.png",
    "сиреневый пепел": "color_images/V426.png",
    "лилово-серый": "color_images/X426.png",
    "пастельный лиловый": "color_images/Y426.png",
    "серебристый водопад": "color_images/H438.png",
    "океанический зеленый": "color_images/L438.png",
    "маренго": "color_images/N438.png",
    "мятно-бирюзовый": "color_images/K441.png",
    "холодный изумрудный": "color_images/M441.png",
    "светлый дымчато-зеленый": "color_images/G444.png",
    "дымчато-зеленый": "color_images/H444.png",
    "тростниковый зеленый": "color_images/J444.png",
    "таинственный лес": "color_images/K444.png",
    "темный хвойный": "color_images/L444.png",
    "таёжный омут": "color_images/M444.png",
    "болотный зеленый": "color_images/N444.png",
    "сланцевый зеленый": "color_images/S444.png",
    "фельдграу": "color_images/V444.png",
    "серо-зеленый": "color_images/J448.png",
    "листья шалфея": "color_images/K448.png",
    "мягкий хвойно-зеленый": "color_images/L448.png",
    "кактус": "color_images/M448.png",
    "зеленый хаки": "color_images/N448.png",
    "милитари": "color_images/S448.png",
    "защитный хаки": "color_images/V448.png",
    "бледный серо-зеленый": "color_images/X448.png",
    "темно-зеленый чай": "color_images/H452.png",
    "мягкий оливковый": "color_images/J452.png",
    "оливковый": "color_images/L452.png",
    "темный оливковый": "color_images/M452.png",
    "лавровый": "color_images/N452.png",
    "Элегантный оливковый": "color_images/S452.png",
    "светлый оливковый": "color_images/V452.png",
    "алебастровый": "color_images/F456.png",
    "жасмин": "color_images/G456.png",
    "шампанское": "color_images/H456.png",
    "сандаловое дерево": "color_images/J456.png",
    "охристо-оливковый": "color_images/K456.png",
    "камыш": "color_images/L456.png",
    "дуб": "color_images/M456.png",
    "античная бронза": "color_images/N456.png",
    "песчаник": "color_images/S456.png",
    "золотисто-песочный": "color_images/V456.png",
    "арахис": "color_images/X456.png",
    "речной перламутр": "color_images/H497.png",
    "серый шелк": "color_images/J497.png",
    "ко`вентри": "color_images/K497.png",
    "серая гавань": "color_images/L497.png",
    "цвет акульей кожи": "color_images/M497.png",
    "цементно-серый": "color_images/N497.png",
    "серый хаки": "color_images/S497.png",
    "земляной серый": "color_images/V497.png",
    "ледниковый серый": "color_images/G499.png",
    "пыльно-серый": "color_images/H499.png",
    "агатовый серый": "color_images/J499.png",
    "титановый": "color_images/K499.png",
    "стальной": "color_images/L499.png",
    "графит": "color_images/M499.png",
    "грифельный серый": "color_images/N499.png",
    "антрацит": "color_images/S499.png",
    "утренний смог": "color_images/F500.png",
    "балтийский туман": "color_images/G500.png",
    "алюминиево-серый": "color_images/H500.png",
    "пепельный": "color_images/J500.png",
    "серый нейтральный": "color_images/K500.png",
    "голубиный серый": "color_images/L500.png",
    "грифельный": "color_images/M500.png",
    "оловянный": "color_images/N500.png",
    "глубокий серый": "color_images/S500.png",
    "гранит": "color_images/V500.png",
    "угольный": "color_images/X500.png"
}

async def update_uf_file(uf_name):
    uf_name_lower = uf_name.lower() if uf_name else ""
    
    # Проверяем частичное совпадение с ключами color_images
    for color_name, path in color_images.items():
        if color_name.lower() in uf_name_lower:
            return path  # Возвращаем путь (например, color_images/V355.png)
    return ""

async def process_xml(input_file, output_file):
    tree = ET.parse(input_file)
    root = tree.getroot()
    tasks = []
    
    for item in root.findall('.//item'):
        id_value = item.find('id').text
        uf_name = item.find('uf_name').text
        uf_xml_id = item.find('uf_xml_id').text
        uf_file = item.find('uf_file')
        
        # Если тег <uf_file> отсутствует, создаем его
        if uf_file is None:
            uf_file = ET.SubElement(item, 'uf_file')
            uf_file.text = ""
        
        if uf_name:
            uf_name_lower = uf_name.lower() if uf_name else ""
            matched_path = ""
            for color_name, path in color_images.items():
                if color_name.lower() in uf_name_lower:
                    matched_path = path  # Полный путь из color_images
                    break
            print(f"ID: {id_value}, uf_name: {uf_name}, Path: {matched_path}")
            task = update_uf_file(uf_name)
            tasks.append((task, uf_file))
    
    results = await asyncio.gather(*(task for task, _ in tasks))
    for (task, uf_file), file_path in zip(tasks, results):
        if file_path:  # Обновляем uf_file только если путь не пустой
            uf_file.text = file_path
    
    tree.write(output_file, encoding='utf-8', xml_declaration=True)

async def main():
    await process_xml("color_full.xml", "output.xml")

if __name__ == "__main__":
    asyncio.run(main())